### ISSUE TITLE
[SYN-20] Test issue from L

### ISSUE THREAD

**Issue by tedspare** [tedspare/synclinear#3]
Desc

<sub>From [SyncLinear.com](https://synclinear.com) | [SYN-20](https://linear.app/rubriclabs/issue/SYN-20/test-issue-from-l)</sub>

**Comment by tedspare** [comment]
comment

**Comment by tedspare** [comment]
test comment now

**Comment by tedspare** [comment]
now it should work

**Comment by tedspare** [comment]
now it should

**Comment by tedspare** [comment]
test

**Comment by tedspare** [comment]
test comment

**Comment by tedspare** [comment]
comment from GH

**Comment by aerosonic-jp** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
gxvr, @adriendarki, @Angular2ES, @BLamy, @guozejun, @macodx, @Dr-ZHUIM, @PengJiyuan, @andreystarkov, @n370, @andsilver, @dalareo, @taoyuan, @h0rizons, @psobusiak, @LijinPengT, @blackwatertepes, @pxseu, @tj-14, @0age, @danlaurent, @newbyca, @Sany07, @davyvong, @nestyxx, @hahalby, @mesirendon, @amedmell, @boardmain, @MariuszWitkowski, @CosmicSkull, @MadelineAu, @fakenickels, @jojo857857, @bspangboldt, @jawang94, @SwathiMystery, @Levero, @DayoWang, @nimrc, @eremitik, @io12, @wwwip, @isensen, @gabrielcald, @dmoss, @plsmaop, @vranystepan, @mimusyun, @ericheayn
